# Generated by Django 2.1.3 on 2019-04-14 12:12
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190406_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('up', models.IntegerField(default=0)),
                ('collection', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='avatar/20190414'), verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='background',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='background/20190414'), verbose_name='背景图'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
    ]
