# Generated by Django 2.1.3 on 2019-04-16 00:22

from django.db import migrations
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190414_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name': '攻略文章', 'verbose_name_plural': '攻略文章'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='avatar/20190416'), verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='background',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to=stdimage.utils.UploadToUUID(path='background/20190416'), verbose_name='背景图'),
        ),
    ]
