# Generated by Django 2.1.3 on 2019-04-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190418_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='s_state',
            field=models.CharField(blank=True, choices=[('review', '审核中'), ('publish', '已发布'), ('nopass', '建议修改')], default='审核中', max_length=32, verbose_name='攻略状态'),
        ),
    ]
