# Generated by Django 2.1.3 on 2019-04-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190419_0020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'ordering': ('title',), 'verbose_name': '攻略文章', 'verbose_name_plural': '攻略文章'},
        ),
        migrations.AddField(
            model_name='strategy',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='strategy_like', to='home.User'),
        ),
    ]
